services:
  web:
    build: .
    container_name: allstarvintage
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./fonts:/usr/share/nginx/html/fonts
      - ./img/logos:/usr/share/nginx/html/img/logos
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  default:
    driver: bridge